services:
  trajectologist_backend:
    build:
      context: './'
      dockerfile: Dockerfile
    container_name: 'trajectologist_backend'
    image: trajectologist
    ports:
      - 3010:3010
    env: './'
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: trajectologist_bd
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DATABASE=trajectologist
    command: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
